flutter_build_ios:
  stage: build
  before_script:
    - flutter packages get
    - flutter clean
  script:
    - flutter build ios
    - cd ios
    - xcodebuild clean archive -workspace Runner.xcworkspace -scheme Runner -archivePath RunnerArchive
    - xcodebuild -exportArchive -archivePath RunnerArchive.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ./build
  artifacts:
    paths:
      - ios/build/Runner.ipa
  tags:
    - flutter