stages:
  - test
  - analyse
  - build

flutter_test:
  rules:
  - if: '$CI_COMMIT_REF_NAME != "beta_test" && $CI_PIPELINE_SOURCE == "push"'
  stage: test
  script:
    - flutter test
  tags:
    - flutter

flutter_analyse:
  rules:
  - if: '$CI_COMMIT_REF_NAME != "beta_test" && $CI_PIPELINE_SOURCE == "push"'
  stage: analyse
  script:
    - analysis_output=$(flutter analyze)
      report_lines="$(echo "$analysis_output" | grep -oE '[0-9]+ issues found' | cut -d ' ' -f 1)"
      if [[ $report_lines -gt 10 ]]; then
          echo "more then 10 issues found"
          exit 1
      fi
  tags:
    - flutter


flutter_build_android:
  stage: build
  before_script:
    - flutter packages get
    - flutter clean
  script:
     - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
  tags:
    - flutter

deploy_google_android:
  stage: deploy
  before_script:
    - cd android
    - bundle install --deployment
  dependencies:
    - flutter_build_android
  script:
    - fastlane deploy_google_drive
  tags:
    - flutter
