stages:
  - test
  - analyse
  - build

flutter_test:
  rules:
  - if: '$CI_COMMIT_REF_NAME != "master" && $CI_PIPELINE_SOURCE == "push"'
  stage: test
  script:
    - flutter test
  tags:
    - flutter

flutter_analyse:
  rules:
  - if: '$CI_COMMIT_REF_NAME != "master" && $CI_PIPELINE_SOURCE == "push"'
  stage: analyse
  script:
    - metrics lib -r codeclimate  > gl-code-quality-report.json
    - |
      report_lines="$(wc -l gl-code-quality-report.json | cut -f1 -d" ")"
      if [[ $report_lines -gt 10 ]]; then
          echo "more then 10 issues found"
          exit 1  # fail the job
      fi
  tags:
    - flutter


futter_build_android:
  stage: build
  before_script:
    - flutter packages get
    - flutter clean
  script:
     - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
  tags:
    - flutter

# Deploy to google drive
