stages:
  - test
#  - analyse
  - build
  - deploy

flutter_test:
  rules:
  - if: '$CI_COMMIT_REF_NAME == "beta-test" && $CI_PIPELINE_SOURCE == "push"'
  stage: test
  script:
    - flutter test
  tags:
    - flutter

#flutter_analyse:
#  rules:
#  - if: '$CI_COMMIT_REF_NAME == "beta-test" && $CI_PIPELINE_SOURCE == "push"'
#  stage: analyse
#  script:
#    - analysis_output=$(flutter analyze)
#      $report_lines = ($analysis_output | Select-String -Pattern '(\d+) issues found').Matches.Groups[1].Value
#      if [[ $report_lines -gt 10 ]]; then
#          echo "more then 10 issues found"
#          exit 1
#      fi
#  tags:
#    - flutter


flutter_build_android:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "beta-test" && $CI_PIPELINE_SOURCE == "push"'
  stage: build
  before_script:
    - flutter packages get
    - flutter clean
  script:
     - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
  tags:
    - flutter

deploy_google_android:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "beta-test" && $CI_PIPELINE_SOURCE == "push"'
  stage: deploy
  before_script:
    - cd android
  dependencies:
    - flutter_build_android
  script:
    - echo "$YOUR_SECRET_VARIABLE" > android/fastlane/drive_key.json || touch android/fastlane/drive_key.json
    - fastlane deploy_google_drive
  tags:
    - flutter
