# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Drive"
  lane :deploy_google_drive do

   upload_to_google_drive(
      drive_keyfile: './fastlane/drive_key.json',
      service_account: true,
      folder_id: '1Znd2NttLhNfVeKTw04vQp4D-f_SUEIeZ',
      upload_files: ['build/app/outputs/apk/release/app-release.apk']
    )
  end
end
